#
###################################
# Site wide configuration
####################################
#
title: Blog
email: agmks@juengling-edv.de
description: Agile Usergroup Kassel
url: https://agile-usergroup-kassel.github.io/blog # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Berlin
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Agile Usergroup Kassel
  avatar: agmks_Logo2017_xing.png
  job: "User Group"
  bio: ""
  email: agmks@juengling-edv.de
  disqus-shortname: agugks
  twitter: AgileUsrgrpKs #username
  facebook: 
  google:
    plus: 
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Agile-Usergroup-Kassel #username
  stackoverflow: 
  linkedin: 
  xing: https://www.xing.com/communities/groups/agile-monday-kassel-98ea-1050362 #link
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
